import type { NextPage } from "next";
import Head from "next/head";

import Header from "components/Header";
import Countries from "components/Countries";
import { Box, useColorModeValue } from "@chakra-ui/react";

import Country from "components/interfaces/Country";
import { countryData } from "components/interfaces/Country";

const Home = ({ countries }: { countries: Country[] }) => {
  const bg = useColorModeValue("white", "secondary");

  return (
    <div>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box bgColor={bg} minH="100vh">
          <Header />
          <Countries countries={countries} />
        </Box>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const countries = await fetch("https://restcountries.com/v3.1/all")
    .then((res) => res.json())
    .then((res) => res.map(countryData));

  return {
    props: { countries },
  };
}
